// Auto-generated brand lookup file
// Generated on: 2025-07-07T22:01:39.216Z
// Total brands: 598

export const BRAND_TIER_LOOKUP: Record<string, string> = {
  "4711": "mass-market",
  "Spezierie Palazzo Vecchio / I Profumi di Firenze": "niche",
  "Henry Jacques": "luxury",
  "Guerlain": "luxury",
  "Avon": "mass-market",
  "Dior": "high-end-designer",
  "Givenchy": "high-end-designer",
  "Galimard": "niche",
  "Fueguia 1833": "niche",
  "Fragonard": "high-end-designer",
  "Yves Saint Laurent": "high-end-designer",
  "Chanel": "high-end-designer",
  "Caron": "luxury",
  "Roja Parfums": "luxury",
  "Bath & Body Works": "mass-market",
  "Shiseido / 資生堂": "high-end-designer",
  "Molinard": "niche",
  "Armaf": "designer",
  "Milton-Lloyd / Jean Yves Cosmetics": "mass-market",
  "Calvin Klein": "designer",
  "Giorgio Armani": "high-end-designer",
  "Estēe Lauder": "high-end-designer",
  "Al Haramain / الحرمين": "niche",
  "Molton Brown": "high-end-designer",
  "Rochas": "designer",
  "Salvatore Ferragamo": "high-end-designer",
  "Houbigant": "luxury",
  "Hugo Boss": "designer",
  "Gucci": "high-end-designer",
  "Amouage": "luxury",
  "Carthusia": "niche",
  "Abdul Samad Al Qurashi / عبدالصمد القرشي": "luxury",
  "s.Oliver": "mass-market",
  "Byredo": "niche",
  "Yves Rocher": "mass-market",
  "Cartier": "luxury",
  "Lancôme": "high-end-designer",
  "Burberry": "high-end-designer",
  "Coty": "mass-market",
  "Kenzo": "designer",
  "Boucheron": "luxury",
  "The Body Shop": "mass-market",
  "Bvlgari": "high-end-designer",
  "Salvador Dali": "designer",
  "Otto Kern": "designer",
  "Ormonde Jayne": "luxury",
  "Ensar Oud / Oriscent": "luxury",
  "Nabeel": "unknown",
  "Lalique": "luxury",
  "Junaid Perfumes": "niche",
  "Mexx": "mass-market",
  "Penhaligon's": "niche",
  "Paco Rabanne": "designer",
  "Goutal": "niche",
  "Nobile 1942": "niche",
  "Bruno Banani": "mass-market",
  "Ralph Lauren": "high-end-designer",
  "Aigner": "designer",
  "Carolina Herrera": "high-end-designer",
  "Floris": "high-end-designer",
  "Swiss Arabian": "niche",
  "Atkinsons": "luxury",
  "Marc Jacobs": "high-end-designer",
  "Balenciaga": "high-end-designer",
  "L'Occitane en Provence": "high-end-designer",
  "The LAB Fragrances": "niche",
  "Nina Ricci": "designer",
  "Acqua di Parma": "luxury",
  "Jean Patou": "luxury",
  "Jil Sander": "designer",
  "The Merchant Of Venice": "luxury",
  "Hermès": "high-end-designer",
  "Elizabeth Arden": "high-end-designer",
  "Lanvin": "designer",
  "Etro": "high-end-designer",
  "Mäurer & Wirtz": "designer",
  "Robert Piguet": "high-end-designer",
  "Eisenberg": "luxury",
  "Angela Flanders": "niche",
  "Tom Ford": "high-end-designer",
  "Lacoste": "designer",
  "Davidoff": "high-end-designer",
  "Joop!": "designer",
  "Perfumers": "niche",
  "Ojar": "unknown",
  "Issey Miyake": "designer",
  "Escada": "designer",
  "Loewe": "luxury",
  "Laura Biagiotti": "designer",
  "La Perla": "luxury",
  "Dana": "mass-market",
  "Dolce & Gabbana": "high-end-designer",
  "Van Cleef & Arpels": "luxury",
  "Chloé": "high-end-designer",
  "Olivier Durbano": "niche",
  "Guy Laroche": "designer",
  "Betty Barclay": "designer",
  "Fendi": "high-end-designer",
  "Jean-Louis Scherrer": "designer",
  "Halston": "designer",
  "David Beckham": "designer",
  "Perris Monte Carlo": "luxury",
  "Balmain": "high-end-designer",
  "Jean Paul Gaultier": "designer",
  "Trussardi": "high-end-designer",
  "Missoni": "high-end-designer",
  "Cerruti": "designer",
  "Ghawali": "luxury",
  "Grès": "designer",
  "Adidas": "mass-market",
  "Elizabeth Taylor": "designer",
  "Dunhill": "high-end-designer",
  "Crabtree & Evelyn": "unknown",
  "Lorenzo Villoresi": "niche",
  "Oscar de la Renta": "high-end-designer",
  "Mugler": "high-end-designer",
  "Afnan Perfumes": "niche",
  "Yardley": "mass-market",
  "Argos": "unknown",
  "Acqua dell'Elba": "niche",
  "Cacharel": "designer",
  "Juicy Couture": "designer",
  "Ohana Mahaalo / オハナ・マハロ": "niche",
  "DKNY / Donna Karan": "designer",
  "Sweet Anthem": "niche",
  "Kenneth Cole": "designer",
  "Azzaro": "designer",
  "Krizia": "designer",
  "Guess": "designer",
  "Narciso Rodriguez": "designer",
  "Gianfranco Ferré": "designer",
  "Clean": "designer",
  "Karl Lagerfeld": "high-end-designer",
  "Tiziana Terenzi": "luxury",
  "soOud": "niche",
  "Philosophy": "designer",
  "California Perfume Company": "unknown",
  "Corday": "unknown",
  "Forage": "niche",
  "Versace": "designer",
  "Prada": "designer",
  "Zara": "mass-market",
  "Acca Kappa": "high-end-designer",
  "Hanae Mori / ハナヱ モリ": "designer",
  "D.S. & Durga": "niche",
  "Farmacia SS. Annunziata": "niche",
  "Harajuku Lovers / Gwen Stefani": "designer",
  "Marbert": "mass-market",
  "Lolita Lempicka": "designer",
  "Histoires de Parfums": "niche",
  "Puma": "mass-market",
  "Santa Maria Novella": "niche",
  "LR / Racine": "unknown",
  "Sabé Masson / Le Soft Perfume": "niche",
  "Réminiscence": "niche",
  "Skylar": "unknown",
  "Gian Marco Venturi": "designer",
  "Tocca": "designer",
  "Chopard": "luxury",
  "Jo Malone": "high-end-designer",
  "XerJoff": "luxury",
  "Gloss Moderne": "luxury",
  "Victoria's Secret": "mass-market",
  "Kilian": "luxury",
  "Durance en Provence": "niche",
  "Gabriela Sabatini": "designer",
  "Fulton & Roark": "niche",
  "Jaguar": "designer",
  "Alexandre.J": "luxury",
  "Britney Spears": "mass-market",
  "Geoffrey Beene": "designer",
  "Brioni": "luxury",
  "Arlyn": "unknown",
  "Léonard": "designer",
  "Ted Lapidus": "designer",
  "bdk Parfums": "niche",
  "Helena Rubinstein": "luxury",
  "Weil": "designer",
  "Knize": "luxury",
  "Venus Spa / ヴィーナススパ": "mass-market",
  "MCM": "high-end-designer",
  "Vera Wang": "designer",
  "My Perfumes": "unknown",
  "Iceberg": "designer",
  "Toni Gard": "designer",
  "Grossmith": "luxury",
  "Diesel": "designer",
  "L'Artisan Parfumeur": "niche",
  "Jacomo": "designer",
  "Paul Smith": "designer",
  "Atelier Austin Press": "niche",
  "El Nabil": "niche",
  "Paris Hilton": "mass-market",
  "Juvena": "unknown",
  "Frau Tonis Parfum": "niche",
  "Sonia Rykiel": "designer",
  "Ex Nihilo": "luxury",
  "Maison Francis Kurkdjian": "niche",
  "DSH Perfumes": "niche",
  "Worth": "high-end-designer",
  "Osmofolia": "niche",
  "Lush / Cosmetics To Go": "niche",
  "Carven": "designer",
  "Oriflame": "unknown",
  "Viktor & Rolf": "high-end-designer",
  "Alfred Sung": "designer",
  "Axe / Lynx": "mass-market",
  "Damask Haus": "niche",
  "Tiffany & Co.": "luxury",
  "Fantôme": "niche",
  "Khaltat / خلطات": "niche",
  "Bahoma": "unknown",
  "Bogner": "high-end-designer",
  "Montblanc": "high-end-designer",
  "Samouraï Woman / サムライウーマン": "unknown",
  "Vince Camuto": "designer",
  "For Strange Women": "niche",
  "Murphy & McNeil": "niche",
  "Good Chemistry": "mass-market",
  "LM Parfums": "niche",
  "Tous": "designer",
  "Tom Tailor": "unknown",
  "Angel Schlesser": "designer",
  "Anna Sui": "designer",
  "Ava Luxe": "niche",
  "Birkholz": "luxury",
  "Sage Machado": "niche",
  "Boadicea the Victorious": "luxury",
  "Royal Mirage": "mass-market",
  "Royal Apothic": "designer",
  "Roccobarocco": "designer",
  "Roberto Capucci": "designer",
  "Rihanna": "designer",
  "Ramón Monegal": "luxury",
  "Puig": "high-end-designer",
  "Pink Sugar": "mass-market",
  "Declaration Grooming / L&L Grooming": "niche",
  "Phlur": "niche",
  "Dorin": "luxury",
  "Paloma Picasso": "designer",
  "Elixir Attar": "niche",
  "Ellen Betrix": "unknown",
  "Ellen Tracy": "designer",
  "Ermenegildo Zegna": "high-end-designer",
  "My Geisha": "unknown",
  "Mila Schön": "high-end-designer",
  "Marc de la Morandière": "niche",
  "James Bond 007": "designer",
  "Lubin": "niche",
  "Lancetti": "designer",
  "Jacques Bogart": "designer",
  "Van Gils": "designer",
  "Myrurgia": "designer",
  "Fanatic": "unknown",
  "Olivine": "niche",
  "Emanuel Ungaro": "designer",
  "Editions de Parfums Frédéric Malle": "niche",
  "Perry Ellis": "designer",
  "Decorté": "luxury",
  "Curve / Liz Claiborne": "designer",
  "ReClassified": "unknown",
  "Jean-Charles Brosseau": "niche",
  "Revillon": "unknown",
  "Clinique": "mass-market",
  "Christina Aguilera": "designer",
  "Caswell-Massey": "high-end-designer",
  "Romeo Gigli": "designer",
  "Bruno Acampora": "niche",
  "Les Perles D'Orient": "niche",
  "Bottega Veneta": "luxury",
  "Les Parfums de Rosine": "niche",
  "Bijan": "luxury",
  "Sarah Jessica Parker": "designer",
  "Sawalef": "niche",
  "Le Labo": "niche",
  "Sunnamusk": "niche",
  "Taylor of London": "unknown",
  "Thameen": "luxury",
  "Ariana Grande": "mass-market",
  "Areej Le Doré": "niche",
  "d'Orsay": "luxury",
  "Katy Perry": "designer",
  "Kiton": "luxury",
  "Jesus del Pozo": "designer",
  "Michael Kors": "high-end-designer",
  "Moresque": "luxury",
  "M. Micallef": "luxury",
  "Moschino": "designer",
  "Panama 1924": "niche",
  "4160 Tuesdays": "niche",
  "Agar Aura": "niche",
  "Al Rehab": "unknown",
  "Alchemic Muse": "niche",
  "Alyssa Ashley": "designer",
  "Amir Oud": "niche",
  "Ard Al Zaafaran / ارض الزعفران التجارية": "unknown",
  "Australian Private Reserve": "niche",
  "Baldessarini": "designer",
  "Basile": "unknown",
  "Beacon Mercantile": "niche",
  "Bond No. 9": "luxury",
  "Botica Botanica": "unknown",
  "Celine": "high-end-designer",
  "Coach": "high-end-designer",
  "Comptoir Sud Pacifique": "niche",
  "Courrèges": "designer",
  "Cristiano Ronaldo": "high-end-designer",
  "Ed Hardy": "mass-market",
  "Enrico Coveri": "designer",
  "Fine'ry": "unknown",
  "Féraud": "high-end-designer",
  "Ga-De": "designer",
  "Geo. F. Trumper": "luxury",
  "Giorgio Beverly Hills": "designer",
  "Heretic": "niche",
  "Jean Marc": "unknown",
  "Jean Marc Paris": "unknown",
  "Jimmy Choo": "designer",
  "John Galliano": "high-end-designer",
  "Lelas": "unknown",
  "Lise Watier": "designer",
  "Lotto": "unknown",
  "Manzana": "unknown",
  "Mazzolari": "niche",
  "Nautica": "designer",
  "Nikos": "designer",
  "Ortigia": "niche",
  "Police": "mass-market",
  "Rancé 1795": "luxury",
  "Samouraï": "niche",
  "Shay & Blue": "niche",
  "Solinotes": "mass-market",
  "The 7 Virtues": "niche",
  "The Harmonist": "luxury",
  "Vasilisa / ヴァシリーサ": "unknown",
  "Victor": "unknown",
  "Wholly Kaw": "niche",
  "Korloff": "luxury",
  "STR8": "mass-market",
  "GDK / Grey de Kouroun": "unknown",
  "Miyaz Perfume": "unknown",
  "Halka B. Organics": "unknown",
  "Carner": "niche",
  "Replay": "designer",
  "Helmut Lang": "designer",
  "Velvet & Sweet Pea's Purrfumery": "niche",
  "Renato Balestra": "high-end-designer",
  "Abou Jamil Perfumery": "unknown",
  "Helan": "niche",
  "A & E - Ariana & Evans": "niche",
  "Prince Matchabelli": "designer",
  "Primark": "mass-market",
  "Filigree & Shadow": "niche",
  "Pola / ポーラ": "luxury",
  "Playboy": "mass-market",
  "Jessica Simpson": "mass-market",
  "Tonino Lamborghini": "luxury",
  "Vilhelm Parfumerie": "niche",
  "Fernanda / フェルナンダ": "mass-market",
  "345 Soap Co.": "unknown",
  "Pino Silvestre": "designer",
  "Demeter Fragrance Library / The Library Of Fragrance": "mass-market",
  "Dorothy Gray": "unknown",
  "Giovanni Bacci": "unknown",
  "Alexandra de Markoff": "high-end-designer",
  "Perlier": "mass-market",
  "Nicolaï / Parfums de Nicolaï": "niche",
  "Alghabra": "unknown",
  "Annayake / アナヤケ": "high-end-designer",
  "Dsquared²": "designer",
  "Nishane": "niche",
  "Dusita": "niche",
  "Le Galion": "niche",
  "Elie Saab": "high-end-designer",
  "Fabergé": "unknown",
  "Aqua Savon / アクア シャボン": "unknown",
  "English Laundry": "designer",
  "Aramis": "designer",
  "Marc-Antoine Barrois": "luxury",
  "Stirling Soap": "niche",
  "Stella McCartney": "designer",
  "Shulton": "unknown",
  "Mauboussin": "luxury",
  "Sergio Tacchini": "designer",
  "Maïssa": "niche",
  "Bait Al Bakhoor": "niche",
  "Banderas": "mass-market",
  "Mercedes-Benz": "high-end-designer",
  "Hamidi Oud & Perfumes": "niche",
  "Battistoni": "luxury",
  "Jo Loves...": "niche",
  "Love Passport / ラブ パスポート": "unknown",
  "Michalsky": "designer",
  "Benetton": "mass-market",
  "Jacques Fath": "designer",
  "Bois 1920": "niche",
  "Sabon": "niche",
  "Attar Collection": "niche",
  "Laboratorio Olfattivo": "niche",
  "Jeanne Arthes": "mass-market",
  "J.F. Schwarzlose Berlin": "niche",
  "House of Matriarch": "niche",
  "Laura Ashley": "designer",
  "Hollister": "mass-market",
  "Hind Al Oud / هند العود": "luxury",
  "Le Monde Gourmand": "niche",
  "Ligne St Barth": "luxury",
  "Heavendüft": "unknown",
  "Widian / AJ Arabia": "niche",
  "Halloween": "mass-market",
  "Luciano Soprani": "designer",
  "Gritti": "luxury",
  "Gloria Vanderbilt": "designer",
  "MCMC Fragrances": "niche",
  "MOR": "designer",
  "Maison Anthony Marmin / Abdul Karim Al Faransi": "niche",
  "Giorgio Valenti": "unknown",
  "Metascent": "unknown",
  "MiN New York": "niche",
  "Germaine Monteil": "unknown",
  "Midnight Gypsy Alchemy": "niche",
  "Gandini": "unknown",
  "Fyrinnae": "unknown",
  "Montale": "niche",
  "Montana": "designer",
  "Morris": "unknown",
  "Flavia": "unknown",
  "Ferrari": "high-end-designer",
  "Mülhens": "unknown",
  "M∙A∙C": "high-end-designer",
  "Naomi Campbell": "designer",
  "Aerin": "high-end-designer",
  "Navitus Parfums": "niche",
  "Adolfo Dominguez": "designer",
  "Nilafar du Nil": "niche",
  "Noble Otter": "niche",
  "Extró": "niche",
  "Acqua di Sardegna": "niche",
  "Electimuss": "unknown",
  "E&S Rasage": "unknown",
  "Duftanker MGO Duftmanufaktur": "niche",
  "Dr. Jon's": "niche",
  "Pierre Guillaume": "niche",
  "De Ruy": "unknown",
  "Daniel Josier": "niche",
  "Rasasi": "designer",
  "Comin": "unknown",
  "Clarins": "high-end-designer",
  "Risingwave / ライジングウェーブ": "unknown",
  "Chiseled Face": "niche",
  "Roberto Cavalli": "high-end-designer",
  "Roberto Ugolini": "unknown",
  "Chevignon": "designer",
  "Chatillon Lux": "niche",
  "Roger & Gallet": "designer",
  "Byblos": "designer",
  "Room 1015": "niche",
  "Roxana Illuminated Perfumes": "niche",
  "S&C Perfumes / Suchel Camacho": "unknown",
  "S.T. Dupont": "high-end-designer",
  "Beyoncé": "high-end-designer",
  "Abercrombie & Fitch": "designer",
  "Sarah Horowitz Parfums": "niche",
  "Sean John": "designer",
  "Serge Lutens": "niche",
  "Sergio Soldano": "designer",
  "Abaton": "unknown",
  "Aēsop": "niche",
  "Zarkoperfume": "niche",
  "Solstice Scents": "niche",
  "Surrati / السرتي": "niche",
  "Tauer Perfumes": "niche",
  "Tcheon Fung Sing": "niche",
  "Arome / Arochem": "unknown",
  "Armand Basi": "designer",
  "ADN Paris": "unknown",
  "Arabiyat": "niche",
  "The Man Company": "unknown",
  "Angel Heart / エンジェルハート": "mass-market",
  "Tommy Bahama": "designer",
  "Tommy Hilfiger": "designer",
  "Tonatto": "niche",
  "Alcina": "unknown",
  "Alchemessence": "niche",
  "Valentino": "high-end-designer",
  "Alain Delon": "unknown",
  "Al Fares / الفارس": "niche",
  "Ajmal": "niche",
  "Agent Provocateur": "designer",
  "Vivienne Westwood": "designer",
  "Khalis / خالص": "niche",
  "Khadlaj / خدلج": "niche",
  "Kanebo": "luxury",
  "L'Antichambre": "niche",
  "L'Erbolario": "designer",
  "La Martina": "high-end-designer",
  "Maison Margiela": "designer",
  "MEM Company / M. E. Mayer": "unknown",
  "Touch of Oud": "niche",
  "Bortnikoff": "niche",
  "Borsari 1870": "niche",
  "Boots": "mass-market",
  "Jōvan": "mass-market",
  "Western Valley": "unknown",
  "Miraculum": "niche",
  "Miller Harris": "niche",
  "Gather Perfume / Amrita Aromatics": "niche",
  "Blumarine": "designer",
  "Black Oud London": "niche",
  "Twinkle Apothecary": "niche",
  "Ulric de Varens": "mass-market",
  "Michel Germain": "designer",
  "Ghost": "designer",
  "Urban Outfitters": "mass-market",
  "Menard": "luxury",
  "Memo Paris": "niche",
  "Scorpio": "unknown",
  "Kosé / コーセー": "mass-market",
  "Jünger & Gebhardt / Patrizier Haus Köln": "niche",
  "Alain Daniel": "unknown",
  "Womo": "unknown",
  "Gissah / قصة": "unknown",
  "Bachs": "unknown",
  "Matière Première": "niche",
  "M. Asam": "mass-market",
  "Al Halal": "unknown",
  "Kuschel J / クシェルヨット": "unknown",
  "Aéropostale": "mass-market",
  "Auric Blends": "niche",
  "Massimo Dutti": "high-end-designer",
  "Marks & Spencer": "mass-market",
  "Aubusson": "designer",
  "Al Aneeq": "unknown",
  "La Rive": "mass-market",
  "Atelier des Ors": "luxury",
  "Heeley": "niche",
  "Arts&Scents": "niche",
  "Lancaster": "high-end-designer",
  "Agua de Baleares": "niche",
  "Expand / エクスパンド": "unknown",
  "One Way Bridge Perfumes": "unknown",
  "Eminence Parfums": "unknown",
  "Orlane / Jean d'Albret": "designer",
  "Emilio Pucci": "designer",
  "Teone Reinthal Natural Perfume": "niche",
  "Ella K Parfums": "niche",
  "ODE / 80 Acres": "niche",
  "2 Note": "unknown",
  "El Charro": "unknown",
  "Zoologist": "niche",
  "Pana Dora": "unknown",
  "100BON": "niche",
  "Panouge": "niche",
  "Parfums de Marly": "luxury",
  "Fabled Fragrances": "niche",
  "Patio": "unknown",
  "Gi. Vi. Emme / Visconti di Modrone": "unknown",
  "Farfalla": "niche",
  "Perfumer's Workshop": "designer",
  "The Good Scent.": "niche",
  "Next": "unknown",
  "Douglas": "mass-market",
  "Natural Looks": "mass-market",
  "Phebo": "designer",
  "Di Ser / ディセル": "niche",
  "Farmasi": "mass-market",
  "Pierre Cardin": "designer",
  "L'Aromatica / Larō": "niche",
  "John Varvatos": "high-end-designer",
  "Napoleon": "unknown",
  "Fiancée / フィアンセ": "unknown",
  "Fila": "mass-market",
  "Yohji Yamamoto": "high-end-designer",
  "Dar Alteeb / دار الطيب": "niche",
  "Finca / フィンカ": "unknown",
  "Fiorucci": "unknown",
  "Procter & Gamble": "mass-market",
  "Aftelier": "niche",
  "Dame Perfumery Scottsdale": "niche",
  "Cuba": "mass-market",
  "Constance Carroll": "mass-market",
  "Flore Botanical Alchemy": "niche",
  "Gilles Cantuel": "niche",
  "RazoRock": "unknown",
  "Comme des Garçons": "designer",
  "Franck Olivier": "designer",
  "Molyneux": "designer",
  "Thomas Kosmala": "niche",
  "Wild Stone": "mass-market",
  "Jennifer Lopez": "designer",
  "Christian Louboutin": "luxury",
  "American Eagle": "mass-market",
  "Alphy & Becs": "high-end-designer",
  "Mancera": "niche",
  "Johann Maria Farina gegenüber dem Jülichs-Platz": "luxury",
  "Kayali": "luxury",
  "Holy Oud": "niche",
  "Frapin": "luxury"
};

export const BRAND_PRICE_RANGE_LOOKUP: Record<string, string> = {
  "4711": "under-50",
  "Spezierie Palazzo Vecchio / I Profumi di Firenze": "150-300",
  "Henry Jacques": "500+",
  "Guerlain": "150-300",
  "Avon": "under-50",
  "Dior": "150-300",
  "Givenchy": "150-300",
  "Galimard": "150-300",
  "Fueguia 1833": "150-300",
  "Fragonard": "50-150",
  "Yves Saint Laurent": "150-300",
  "Chanel": "150-300",
  "Caron": "150-300",
  "Roja Parfums": "300-500",
  "Bath & Body Works": "under-50",
  "Shiseido / 資生堂": "150-300",
  "Molinard": "150-300",
  "Armaf": "50-150",
  "Milton-Lloyd / Jean Yves Cosmetics": "under-50",
  "Calvin Klein": "50-150",
  "Giorgio Armani": "150-300",
  "Estēe Lauder": "50-150",
  "Al Haramain / الحرمين": "unknown",
  "Molton Brown": "50-150",
  "Rochas": "50-150",
  "Salvatore Ferragamo": "150-300",
  "Houbigant": "300-500",
  "Hugo Boss": "50-150",
  "Gucci": "150-300",
  "Amouage": "300-500",
  "Carthusia": "150-300",
  "Abdul Samad Al Qurashi / عبدالصمد القرشي": "300-500",
  "s.Oliver": "under-50",
  "Byredo": "150-300",
  "Yves Rocher": "under-50",
  "Cartier": "300-500",
  "Lancôme": "50-150",
  "Burberry": "150-300",
  "Coty": "under-50",
  "Kenzo": "50-150",
  "Boucheron": "300-500",
  "The Body Shop": "under-50",
  "Bvlgari": "150-300",
  "Salvador Dali": "50-150",
  "Otto Kern": "50-150",
  "Ormonde Jayne": "300-500",
  "Ensar Oud / Oriscent": "300-500",
  "Nabeel": "unknown",
  "Lalique": "150-300",
  "Junaid Perfumes": "unknown",
  "Mexx": "under-50",
  "Penhaligon's": "150-300",
  "Paco Rabanne": "50-150",
  "Goutal": "150-300",
  "Nobile 1942": "150-300",
  "Bruno Banani": "under-50",
  "Ralph Lauren": "150-300",
  "Aigner": "50-150",
  "Carolina Herrera": "150-300",
  "Floris": "150-300",
  "Swiss Arabian": "50-150",
  "Atkinsons": "150-300",
  "Marc Jacobs": "50-150",
  "Balenciaga": "150-300",
  "L'Occitane en Provence": "50-150",
  "The LAB Fragrances": "150-300",
  "Nina Ricci": "50-150",
  "Acqua di Parma": "150-300",
  "Jean Patou": "300-500",
  "Jil Sander": "150-300",
  "The Merchant Of Venice": "150-300",
  "Hermès": "150-300",
  "Elizabeth Arden": "50-150",
  "Lanvin": "50-150",
  "Etro": "150-300",
  "Mäurer & Wirtz": "50-150",
  "Robert Piguet": "150-300",
  "Eisenberg": "150-300",
  "Angela Flanders": "150-300",
  "Tom Ford": "150-300",
  "Lacoste": "50-150",
  "Davidoff": "50-150",
  "Joop!": "50-150",
  "Perfumers": "150-300",
  "Ojar": "unknown",
  "Issey Miyake": "50-150",
  "Escada": "50-150",
  "Loewe": "150-300",
  "Laura Biagiotti": "50-150",
  "La Perla": "150-300",
  "Dana": "under-50",
  "Dolce & Gabbana": "150-300",
  "Van Cleef & Arpels": "150-300",
  "Chloé": "150-300",
  "Olivier Durbano": "150-300",
  "Guy Laroche": "50-150",
  "Betty Barclay": "50-150",
  "Fendi": "150-300",
  "Jean-Louis Scherrer": "150-300",
  "Halston": "50-150",
  "David Beckham": "50-150",
  "Perris Monte Carlo": "300-500",
  "Balmain": "150-300",
  "Jean Paul Gaultier": "50-150",
  "Trussardi": "150-300",
  "Missoni": "150-300",
  "Cerruti": "50-150",
  "Ghawali": "150-300",
  "Grès": "50-150",
  "Adidas": "under-50",
  "Elizabeth Taylor": "under-50",
  "Dunhill": "150-300",
  "Crabtree & Evelyn": "unknown",
  "Lorenzo Villoresi": "150-300",
  "Oscar de la Renta": "150-300",
  "Mugler": "150-300",
  "Afnan Perfumes": "50-150",
  "Yardley": "under-50",
  "Argos": "unknown",
  "Acqua dell'Elba": "150-300",
  "Cacharel": "50-150",
  "Juicy Couture": "50-150",
  "Ohana Mahaalo / オハナ・マハロ": "150-300",
  "DKNY / Donna Karan": "50-150",
  "Sweet Anthem": "unknown",
  "Kenneth Cole": "50-150",
  "Azzaro": "50-150",
  "Krizia": "150-300",
  "Guess": "50-150",
  "Narciso Rodriguez": "150-300",
  "Gianfranco Ferré": "150-300",
  "Clean": "under-50",
  "Karl Lagerfeld": "150-300",
  "Tiziana Terenzi": "300-500",
  "soOud": "150-300",
  "Philosophy": "under-50",
  "California Perfume Company": "unknown",
  "Corday": "unknown",
  "Forage": "150-300",
  "Versace": "50-150",
  "Prada": "150-300",
  "Zara": "under-50",
  "Acca Kappa": "50-150",
  "Hanae Mori / ハナヱ モリ": "50-150",
  "D.S. & Durga": "150-300",
  "Farmacia SS. Annunziata": "150-300",
  "Harajuku Lovers / Gwen Stefani": "50-150",
  "Marbert": "under-50",
  "Lolita Lempicka": "50-150",
  "Histoires de Parfums": "150-300",
  "Puma": "under-50",
  "Santa Maria Novella": "150-300",
  "LR / Racine": "unknown",
  "Sabé Masson / Le Soft Perfume": "50-150",
  "Réminiscence": "150-300",
  "Skylar": "unknown",
  "Gian Marco Venturi": "50-150",
  "Tocca": "50-150",
  "Chopard": "300-500",
  "Jo Malone": "150-300",
  "XerJoff": "300-500",
  "Gloss Moderne": "150-300",
  "Victoria's Secret": "under-50",
  "Kilian": "300-500",
  "Durance en Provence": "50-150",
  "Gabriela Sabatini": "50-150",
  "Fulton & Roark": "50-150",
  "Jaguar": "50-150",
  "Alexandre.J": "150-300",
  "Britney Spears": "under-50",
  "Geoffrey Beene": "50-150",
  "Brioni": "300-500",
  "Arlyn": "unknown",
  "Léonard": "50-150",
  "Ted Lapidus": "50-150",
  "bdk Parfums": "150-300",
  "Helena Rubinstein": "unknown",
  "Weil": "unknown",
  "Knize": "150-300",
  "Venus Spa / ヴィーナススパ": "under-50",
  "MCM": "150-300",
  "Vera Wang": "50-150",
  "My Perfumes": "unknown",
  "Iceberg": "50-150",
  "Toni Gard": "150-300",
  "Grossmith": "300-500",
  "Diesel": "50-150",
  "L'Artisan Parfumeur": "150-300",
  "Jacomo": "50-150",
  "Paul Smith": "50-150",
  "Atelier Austin Press": "150-300",
  "El Nabil": "unknown",
  "Paris Hilton": "under-50",
  "Juvena": "unknown",
  "Frau Tonis Parfum": "150-300",
  "Sonia Rykiel": "50-150",
  "Ex Nihilo": "300-500",
  "Maison Francis Kurkdjian": "150-300",
  "DSH Perfumes": "150-300",
  "Worth": "150-300",
  "Osmofolia": "150-300",
  "Lush / Cosmetics To Go": "under-50",
  "Carven": "50-150",
  "Oriflame": "unknown",
  "Viktor & Rolf": "150-300",
  "Alfred Sung": "50-150",
  "Axe / Lynx": "under-50",
  "Damask Haus": "150-300",
  "Tiffany & Co.": "300-500",
  "Fantôme": "150-300",
  "Khaltat / خلطات": "150-300",
  "Bahoma": "unknown",
  "Bogner": "150-300",
  "Montblanc": "50-150",
  "Samouraï Woman / サムライウーマン": "unknown",
  "Vince Camuto": "50-150",
  "For Strange Women": "50-150",
  "Murphy & McNeil": "unknown",
  "Good Chemistry": "under-50",
  "LM Parfums": "150-300",
  "Tous": "50-150",
  "Tom Tailor": "unknown",
  "Angel Schlesser": "50-150",
  "Anna Sui": "50-150",
  "Ava Luxe": "50-150",
  "Birkholz": "300-500",
  "Sage Machado": "150-300",
  "Boadicea the Victorious": "300-500",
  "Royal Mirage": "under-50",
  "Royal Apothic": "50-150",
  "Roccobarocco": "50-150",
  "Roberto Capucci": "150-300",
  "Rihanna": "50-150",
  "Ramón Monegal": "300-500",
  "Puig": "150-300",
  "Pink Sugar": "under-50",
  "Declaration Grooming / L&L Grooming": "unknown",
  "Phlur": "50-150",
  "Dorin": "150-300",
  "Paloma Picasso": "50-150",
  "Elixir Attar": "150-300",
  "Ellen Betrix": "unknown",
  "Ellen Tracy": "50-150",
  "Ermenegildo Zegna": "150-300",
  "My Geisha": "unknown",
  "Mila Schön": "150-300",
  "Marc de la Morandière": "150-300",
  "James Bond 007": "50-150",
  "Lubin": "150-300",
  "Lancetti": "50-150",
  "Jacques Bogart": "50-150",
  "Van Gils": "50-150",
  "Myrurgia": "50-150",
  "Fanatic": "unknown",
  "Olivine": "unknown",
  "Emanuel Ungaro": "150-300",
  "Editions de Parfums Frédéric Malle": "150-300",
  "Perry Ellis": "50-150",
  "Decorté": "150-300",
  "Curve / Liz Claiborne": "50-150",
  "ReClassified": "unknown",
  "Jean-Charles Brosseau": "150-300",
  "Revillon": "unknown",
  "Clinique": "under-50",
  "Christina Aguilera": "under-50",
  "Caswell-Massey": "50-150",
  "Romeo Gigli": "150-300",
  "Bruno Acampora": "150-300",
  "Les Perles D'Orient": "150-300",
  "Bottega Veneta": "150-300",
  "Les Parfums de Rosine": "150-300",
  "Bijan": "300-500",
  "Sarah Jessica Parker": "under-50",
  "Sawalef": "150-300",
  "Le Labo": "150-300",
  "Sunnamusk": "150-300",
  "Taylor of London": "unknown",
  "Thameen": "300-500",
  "Ariana Grande": "under-50",
  "Areej Le Doré": "300-500",
  "d'Orsay": "150-300",
  "Katy Perry": "under-50",
  "Kiton": "300-500",
  "Jesus del Pozo": "50-150",
  "Michael Kors": "150-300",
  "Moresque": "300-500",
  "M. Micallef": "300-500",
  "Moschino": "50-150",
  "Panama 1924": "150-300",
  "4160 Tuesdays": "50-150",
  "Agar Aura": "150-300",
  "Al Rehab": "under-50",
  "Alchemic Muse": "under-50",
  "Alyssa Ashley": "under-50",
  "Amir Oud": "150-300",
  "Ard Al Zaafaran / ارض الزعفران التجارية": "unknown",
  "Australian Private Reserve": "150-300",
  "Baldessarini": "50-150",
  "Basile": "unknown",
  "Beacon Mercantile": "unknown",
  "Bond No. 9": "300-500",
  "Botica Botanica": "unknown",
  "Celine": "150-300",
  "Coach": "50-150",
  "Comptoir Sud Pacifique": "50-150",
  "Courrèges": "150-300",
  "Cristiano Ronaldo": "50-150",
  "Ed Hardy": "50-150",
  "Enrico Coveri": "50-150",
  "Fine'ry": "unknown",
  "Féraud": "150-300",
  "Ga-De": "50-150",
  "Geo. F. Trumper": "150-300",
  "Giorgio Beverly Hills": "50-150",
  "Heretic": "150-300",
  "Jean Marc": "unknown",
  "Jean Marc Paris": "unknown",
  "Jimmy Choo": "150-300",
  "John Galliano": "150-300",
  "Lelas": "unknown",
  "Lise Watier": "50-150",
  "Lotto": "unknown",
  "Manzana": "unknown",
  "Mazzolari": "150-300",
  "Nautica": "50-150",
  "Nikos": "50-150",
  "Ortigia": "150-300",
  "Police": "under-50",
  "Rancé 1795": "150-300",
  "Samouraï": "150-300",
  "Shay & Blue": "50-150",
  "Solinotes": "under-50",
  "The 7 Virtues": "50-150",
  "The Harmonist": "300-500",
  "Vasilisa / ヴァシリーサ": "unknown",
  "Victor": "unknown",
  "Wholly Kaw": "unknown",
  "Korloff": "300-500",
  "STR8": "under-50",
  "GDK / Grey de Kouroun": "unknown",
  "Miyaz Perfume": "unknown",
  "Halka B. Organics": "unknown",
  "Carner": "150-300",
  "Replay": "50-150",
  "Helmut Lang": "150-300",
  "Velvet & Sweet Pea's Purrfumery": "150-300",
  "Renato Balestra": "150-300",
  "Abou Jamil Perfumery": "unknown",
  "Helan": "unknown",
  "A & E - Ariana & Evans": "50-150",
  "Prince Matchabelli": "unknown",
  "Primark": "under-50",
  "Filigree & Shadow": "150-300",
  "Pola / ポーラ": "300-500",
  "Playboy": "under-50",
  "Jessica Simpson": "under-50",
  "Tonino Lamborghini": "300-500",
  "Vilhelm Parfumerie": "150-300",
  "Fernanda / フェルナンダ": "under-50",
  "345 Soap Co.": "unknown",
  "Pino Silvestre": "under-50",
  "Demeter Fragrance Library / The Library Of Fragrance": "under-50",
  "Dorothy Gray": "unknown",
  "Giovanni Bacci": "unknown",
  "Alexandra de Markoff": "150-300",
  "Perlier": "under-50",
  "Nicolaï / Parfums de Nicolaï": "150-300",
  "Alghabra": "unknown",
  "Annayake / アナヤケ": "150-300",
  "Dsquared²": "50-150",
  "Nishane": "150-300",
  "Dusita": "150-300",
  "Le Galion": "150-300",
  "Elie Saab": "150-300",
  "Fabergé": "unknown",
  "Aqua Savon / アクア シャボン": "unknown",
  "English Laundry": "50-150",
  "Aramis": "50-150",
  "Marc-Antoine Barrois": "300-500",
  "Stirling Soap": "under-50",
  "Stella McCartney": "150-300",
  "Shulton": "unknown",
  "Mauboussin": "150-300",
  "Sergio Tacchini": "50-150",
  "Maïssa": "150-300",
  "Bait Al Bakhoor": "unknown",
  "Banderas": "under-50",
  "Mercedes-Benz": "50-150",
  "Hamidi Oud & Perfumes": "150-300",
  "Battistoni": "300-500",
  "Jo Loves...": "150-300",
  "Love Passport / ラブ パスポート": "unknown",
  "Michalsky": "50-150",
  "Benetton": "under-50",
  "Jacques Fath": "150-300",
  "Bois 1920": "150-300",
  "Sabon": "50-150",
  "Attar Collection": "150-300",
  "Laboratorio Olfattivo": "150-300",
  "Jeanne Arthes": "under-50",
  "J.F. Schwarzlose Berlin": "150-300",
  "House of Matriarch": "150-300",
  "Laura Ashley": "50-150",
  "Hollister": "under-50",
  "Hind Al Oud / هند العود": "300-500",
  "Le Monde Gourmand": "150-300",
  "Ligne St Barth": "150-300",
  "Heavendüft": "unknown",
  "Widian / AJ Arabia": "150-300",
  "Halloween": "under-50",
  "Luciano Soprani": "50-150",
  "Gritti": "150-300",
  "Gloria Vanderbilt": "under-50",
  "MCMC Fragrances": "50-150",
  "MOR": "50-150",
  "Maison Anthony Marmin / Abdul Karim Al Faransi": "150-300",
  "Giorgio Valenti": "unknown",
  "Metascent": "unknown",
  "MiN New York": "150-300",
  "Germaine Monteil": "unknown",
  "Midnight Gypsy Alchemy": "unknown",
  "Gandini": "unknown",
  "Fyrinnae": "unknown",
  "Montale": "150-300",
  "Montana": "50-150",
  "Morris": "unknown",
  "Flavia": "unknown",
  "Ferrari": "50-150",
  "Mülhens": "unknown",
  "M∙A∙C": "50-150",
  "Naomi Campbell": "under-50",
  "Aerin": "150-300",
  "Navitus Parfums": "150-300",
  "Adolfo Dominguez": "50-150",
  "Nilafar du Nil": "150-300",
  "Noble Otter": "50-150",
  "Extró": "150-300",
  "Acqua di Sardegna": "150-300",
  "Electimuss": "unknown",
  "E&S Rasage": "unknown",
  "Duftanker MGO Duftmanufaktur": "150-300",
  "Dr. Jon's": "50-150",
  "Pierre Guillaume": "150-300",
  "De Ruy": "unknown",
  "Daniel Josier": "150-300",
  "Rasasi": "50-150",
  "Comin": "unknown",
  "Clarins": "50-150",
  "Risingwave / ライジングウェーブ": "unknown",
  "Chiseled Face": "50-150",
  "Roberto Cavalli": "150-300",
  "Roberto Ugolini": "unknown",
  "Chevignon": "50-150",
  "Chatillon Lux": "unknown",
  "Roger & Gallet": "50-150",
  "Byblos": "50-150",
  "Room 1015": "150-300",
  "Roxana Illuminated Perfumes": "150-300",
  "S&C Perfumes / Suchel Camacho": "unknown",
  "S.T. Dupont": "150-300",
  "Beyoncé": "50-150",
  "Abercrombie & Fitch": "50-150",
  "Sarah Horowitz Parfums": "150-300",
  "Sean John": "50-150",
  "Serge Lutens": "150-300",
  "Sergio Soldano": "50-150",
  "Abaton": "unknown",
  "Aēsop": "150-300",
  "Zarkoperfume": "150-300",
  "Solstice Scents": "50-150",
  "Surrati / السرتي": "unknown",
  "Tauer Perfumes": "150-300",
  "Tcheon Fung Sing": "150-300",
  "Arome / Arochem": "unknown",
  "Armand Basi": "50-150",
  "ADN Paris": "unknown",
  "Arabiyat": "150-300",
  "The Man Company": "unknown",
  "Angel Heart / エンジェルハート": "under-50",
  "Tommy Bahama": "50-150",
  "Tommy Hilfiger": "50-150",
  "Tonatto": "150-300",
  "Alcina": "unknown",
  "Alchemessence": "150-300",
  "Valentino": "150-300",
  "Alain Delon": "unknown",
  "Al Fares / الفارس": "150-300",
  "Ajmal": "150-300",
  "Agent Provocateur": "50-150",
  "Vivienne Westwood": "150-300",
  "Khalis / خالص": "unknown",
  "Khadlaj / خدلج": "150-300",
  "Kanebo": "150-300",
  "L'Antichambre": "150-300",
  "L'Erbolario": "50-150",
  "La Martina": "150-300",
  "Maison Margiela": "150-300",
  "MEM Company / M. E. Mayer": "unknown",
  "Touch of Oud": "150-300",
  "Bortnikoff": "150-300",
  "Borsari 1870": "150-300",
  "Boots": "under-50",
  "Jōvan": "under-50",
  "Western Valley": "unknown",
  "Miraculum": "150-300",
  "Miller Harris": "150-300",
  "Gather Perfume / Amrita Aromatics": "unknown",
  "Blumarine": "150-300",
  "Black Oud London": "150-300",
  "Twinkle Apothecary": "under-50",
  "Ulric de Varens": "under-50",
  "Michel Germain": "50-150",
  "Ghost": "50-150",
  "Urban Outfitters": "under-50",
  "Menard": "unknown",
  "Memo Paris": "150-300",
  "Scorpio": "unknown",
  "Kosé / コーセー": "unknown",
  "Jünger & Gebhardt / Patrizier Haus Köln": "150-300",
  "Alain Daniel": "unknown",
  "Womo": "unknown",
  "Gissah / قصة": "unknown",
  "Bachs": "unknown",
  "Matière Première": "150-300",
  "M. Asam": "50-150",
  "Al Halal": "unknown",
  "Kuschel J / クシェルヨット": "unknown",
  "Aéropostale": "under-50",
  "Auric Blends": "50-150",
  "Massimo Dutti": "150-300",
  "Marks & Spencer": "under-50",
  "Aubusson": "50-150",
  "Al Aneeq": "unknown",
  "La Rive": "under-50",
  "Atelier des Ors": "300-500",
  "Heeley": "150-300",
  "Arts&Scents": "150-300",
  "Lancaster": "50-150",
  "Agua de Baleares": "150-300",
  "Expand / エクスパンド": "unknown",
  "One Way Bridge Perfumes": "unknown",
  "Eminence Parfums": "unknown",
  "Orlane / Jean d'Albret": "unknown",
  "Emilio Pucci": "150-300",
  "Teone Reinthal Natural Perfume": "150-300",
  "Ella K Parfums": "150-300",
  "ODE / 80 Acres": "unknown",
  "2 Note": "unknown",
  "El Charro": "unknown",
  "Zoologist": "150-300",
  "Pana Dora": "unknown",
  "100BON": "under-50",
  "Panouge": "150-300",
  "Parfums de Marly": "300-500",
  "Fabled Fragrances": "150-300",
  "Patio": "unknown",
  "Gi. Vi. Emme / Visconti di Modrone": "unknown",
  "Farfalla": "unknown",
  "Perfumer's Workshop": "50-150",
  "The Good Scent.": "unknown",
  "Next": "unknown",
  "Douglas": "under-50",
  "Natural Looks": "under-50",
  "Phebo": "50-150",
  "Di Ser / ディセル": "150-300",
  "Farmasi": "under-50",
  "Pierre Cardin": "50-150",
  "L'Aromatica / Larō": "unknown",
  "John Varvatos": "150-300",
  "Napoleon": "unknown",
  "Fiancée / フィアンセ": "unknown",
  "Fila": "under-50",
  "Yohji Yamamoto": "150-300",
  "Dar Alteeb / دار الطيب": "150-300",
  "Finca / フィンカ": "unknown",
  "Fiorucci": "unknown",
  "Procter & Gamble": "under-50",
  "Aftelier": "150-300",
  "Dame Perfumery Scottsdale": "50-150",
  "Cuba": "under-50",
  "Constance Carroll": "under-50",
  "Flore Botanical Alchemy": "150-300",
  "Gilles Cantuel": "150-300",
  "RazoRock": "unknown",
  "Comme des Garçons": "150-300",
  "Franck Olivier": "50-150",
  "Molyneux": "unknown",
  "Thomas Kosmala": "150-300",
  "Wild Stone": "under-50",
  "Jennifer Lopez": "50-150",
  "Christian Louboutin": "300-500",
  "American Eagle": "under-50",
  "Alphy & Becs": "150-300",
  "Mancera": "150-300",
  "Johann Maria Farina gegenüber dem Jülichs-Platz": "300-500",
  "Kayali": "150-300",
  "Holy Oud": "150-300",
  "Frapin": "150-300"
};

export const BRAND_CONFIDENCE_LOOKUP: Record<string, number> = {
  "4711": 0.85,
  "Spezierie Palazzo Vecchio / I Profumi di Firenze": 0.95,
  "Henry Jacques": 0.9,
  "Guerlain": 0.95,
  "Avon": 0.85,
  "Dior": 0.95,
  "Givenchy": 0.95,
  "Galimard": 0.85,
  "Fueguia 1833": 0.85,
  "Fragonard": 0.85,
  "Yves Saint Laurent": 0.95,
  "Chanel": 0.95,
  "Caron": 0.95,
  "Roja Parfums": 0.95,
  "Bath & Body Works": 0.85,
  "Shiseido / 資生堂": 0.85,
  "Molinard": 0.85,
  "Armaf": 0.85,
  "Milton-Lloyd / Jean Yves Cosmetics": 0.85,
  "Calvin Klein": 0.9,
  "Giorgio Armani": 0.95,
  "Estēe Lauder": 0.85,
  "Al Haramain / الحرمين": 0.85,
  "Molton Brown": 0.9,
  "Rochas": 0.85,
  "Salvatore Ferragamo": 0.95,
  "Houbigant": 0.85,
  "Hugo Boss": 0.85,
  "Gucci": 0.95,
  "Amouage": 0.95,
  "Carthusia": 0.85,
  "Abdul Samad Al Qurashi / عبدالصمد القرشي": 0.85,
  "s.Oliver": 0.85,
  "Byredo": 0.95,
  "Yves Rocher": 0.85,
  "Cartier": 0.95,
  "Lancôme": 0.9,
  "Burberry": 0.9,
  "Coty": 0.85,
  "Kenzo": 0.85,
  "Boucheron": 0.95,
  "The Body Shop": 0.9,
  "Bvlgari": 0.9,
  "Salvador Dali": 0.85,
  "Otto Kern": 0.85,
  "Ormonde Jayne": 0.95,
  "Ensar Oud / Oriscent": 0.85,
  "Nabeel": 0.85,
  "Lalique": 0.85,
  "Junaid Perfumes": 0.85,
  "Mexx": 0.85,
  "Penhaligon's": 0.95,
  "Paco Rabanne": 0.85,
  "Goutal": 0.95,
  "Nobile 1942": 0.85,
  "Bruno Banani": 0.85,
  "Ralph Lauren": 0.9,
  "Aigner": 0.85,
  "Carolina Herrera": 0.85,
  "Floris": 0.85,
  "Swiss Arabian": 0.85,
  "Atkinsons": 0.85,
  "Marc Jacobs": 0.9,
  "Balenciaga": 0.85,
  "L'Occitane en Provence": 0.9,
  "The LAB Fragrances": 0.85,
  "Nina Ricci": 0.85,
  "Acqua di Parma": 0.95,
  "Jean Patou": 0.85,
  "Jil Sander": 0.85,
  "The Merchant Of Venice": 0.85,
  "Hermès": 0.95,
  "Elizabeth Arden": 0.9,
  "Lanvin": 0.85,
  "Etro": 0.85,
  "Mäurer & Wirtz": 0.85,
  "Robert Piguet": 0.85,
  "Eisenberg": 0.85,
  "Angela Flanders": 0.85,
  "Tom Ford": 0.95,
  "Lacoste": 0.9,
  "Davidoff": 0.9,
  "Joop!": 0.85,
  "Perfumers": 0.85,
  "Ojar": 0.85,
  "Issey Miyake": 0.9,
  "Escada": 0.85,
  "Loewe": 0.85,
  "Laura Biagiotti": 0.85,
  "La Perla": 0.85,
  "Dana": 0.85,
  "Dolce & Gabbana": 0.95,
  "Van Cleef & Arpels": 0.9,
  "Chloé": 0.9,
  "Olivier Durbano": 0.85,
  "Guy Laroche": 0.85,
  "Betty Barclay": 0.85,
  "Fendi": 0.85,
  "Jean-Louis Scherrer": 0.85,
  "Halston": 0.85,
  "David Beckham": 0.85,
  "Perris Monte Carlo": 0.85,
  "Balmain": 0.85,
  "Jean Paul Gaultier": 0.85,
  "Trussardi": 0.85,
  "Missoni": 0.85,
  "Cerruti": 0.85,
  "Ghawali": 0.85,
  "Grès": 0.85,
  "Adidas": 0.85,
  "Elizabeth Taylor": 0.85,
  "Dunhill": 0.85,
  "Crabtree & Evelyn": 0.85,
  "Lorenzo Villoresi": 0.95,
  "Oscar de la Renta": 0.85,
  "Mugler": 0.95,
  "Afnan Perfumes": 0.85,
  "Yardley": 0.85,
  "Argos": 0.85,
  "Acqua dell'Elba": 0.85,
  "Cacharel": 0.85,
  "Juicy Couture": 0.9,
  "Ohana Mahaalo / オハナ・マハロ": 0.85,
  "DKNY / Donna Karan": 0.9,
  "Sweet Anthem": 0.85,
  "Kenneth Cole": 0.85,
  "Azzaro": 0.85,
  "Krizia": 0.85,
  "Guess": 0.85,
  "Narciso Rodriguez": 0.9,
  "Gianfranco Ferré": 0.85,
  "Clean": 0.85,
  "Karl Lagerfeld": 0.85,
  "Tiziana Terenzi": 0.95,
  "soOud": 0.85,
  "Philosophy": 0.85,
  "California Perfume Company": 0.85,
  "Corday": 0.85,
  "Forage": 0.85,
  "Versace": 0.9,
  "Prada": 0.9,
  "Zara": 0.85,
  "Acca Kappa": 0.85,
  "Hanae Mori / ハナヱ モリ": 0.85,
  "D.S. & Durga": 0.95,
  "Farmacia SS. Annunziata": 0.85,
  "Harajuku Lovers / Gwen Stefani": 0.85,
  "Marbert": 0.85,
  "Lolita Lempicka": 0.85,
  "Histoires de Parfums": 0.85,
  "Puma": 0.85,
  "Santa Maria Novella": 0.95,
  "LR / Racine": 0.85,
  "Sabé Masson / Le Soft Perfume": 0.85,
  "Réminiscence": 0.85,
  "Skylar": 0.85,
  "Gian Marco Venturi": 0.85,
  "Tocca": 0.85,
  "Chopard": 0.85,
  "Jo Malone": 0.95,
  "XerJoff": 0.95,
  "Gloss Moderne": 0.85,
  "Victoria's Secret": 0.9,
  "Kilian": 0.9,
  "Durance en Provence": 0.85,
  "Gabriela Sabatini": 0.85,
  "Fulton & Roark": 0.85,
  "Jaguar": 0.85,
  "Alexandre.J": 0.85,
  "Britney Spears": 0.85,
  "Geoffrey Beene": 0.85,
  "Brioni": 0.85,
  "Arlyn": 0.85,
  "Léonard": 0.85,
  "Ted Lapidus": 0.85,
  "bdk Parfums": 0.85,
  "Helena Rubinstein": 0.85,
  "Weil": 0.85,
  "Knize": 0.85,
  "Venus Spa / ヴィーナススパ": 0.85,
  "MCM": 0.85,
  "Vera Wang": 0.85,
  "My Perfumes": 0.85,
  "Iceberg": 0.85,
  "Toni Gard": 0.85,
  "Grossmith": 0.85,
  "Diesel": 0.85,
  "L'Artisan Parfumeur": 0.95,
  "Jacomo": 0.85,
  "Paul Smith": 0.85,
  "Atelier Austin Press": 0.85,
  "El Nabil": 0.85,
  "Paris Hilton": 0.9,
  "Juvena": 0.85,
  "Frau Tonis Parfum": 0.85,
  "Sonia Rykiel": 0.85,
  "Ex Nihilo": 0.85,
  "Maison Francis Kurkdjian": 0.95,
  "DSH Perfumes": 0.85,
  "Worth": 0.85,
  "Osmofolia": 0.85,
  "Lush / Cosmetics To Go": 0.9,
  "Carven": 0.85,
  "Oriflame": 0.85,
  "Viktor & Rolf": 0.95,
  "Alfred Sung": 0.85,
  "Axe / Lynx": 0.85,
  "Damask Haus": 0.85,
  "Tiffany & Co.": 0.9,
  "Fantôme": 0.85,
  "Khaltat / خلطات": 0.85,
  "Bahoma": 0.85,
  "Bogner": 0.85,
  "Montblanc": 0.85,
  "Samouraï Woman / サムライウーマン": 0.85,
  "Vince Camuto": 0.85,
  "For Strange Women": 0.85,
  "Murphy & McNeil": 0.85,
  "Good Chemistry": 0.85,
  "LM Parfums": 0.85,
  "Tous": 0.85,
  "Tom Tailor": 0.85,
  "Angel Schlesser": 0.85,
  "Anna Sui": 0.85,
  "Ava Luxe": 0.85,
  "Birkholz": 0.85,
  "Sage Machado": 0.85,
  "Boadicea the Victorious": 0.95,
  "Royal Mirage": 0.85,
  "Royal Apothic": 0.85,
  "Roccobarocco": 0.85,
  "Roberto Capucci": 0.85,
  "Rihanna": 0.85,
  "Ramón Monegal": 0.85,
  "Puig": 0.85,
  "Pink Sugar": 0.85,
  "Declaration Grooming / L&L Grooming": 0.85,
  "Phlur": 0.85,
  "Dorin": 0.85,
  "Paloma Picasso": 0.85,
  "Elixir Attar": 0.85,
  "Ellen Betrix": 0.85,
  "Ellen Tracy": 0.85,
  "Ermenegildo Zegna": 0.9,
  "My Geisha": 0.85,
  "Mila Schön": 0.85,
  "Marc de la Morandière": 0.85,
  "James Bond 007": 0.85,
  "Lubin": 0.85,
  "Lancetti": 0.85,
  "Jacques Bogart": 0.85,
  "Van Gils": 0.85,
  "Myrurgia": 0.85,
  "Fanatic": 0.85,
  "Olivine": 0.85,
  "Emanuel Ungaro": 0.85,
  "Editions de Parfums Frédéric Malle": 0.95,
  "Perry Ellis": 0.85,
  "Decorté": 0.85,
  "Curve / Liz Claiborne": 0.85,
  "ReClassified": 0.8,
  "Jean-Charles Brosseau": 0.85,
  "Revillon": 0.85,
  "Clinique": 0.85,
  "Christina Aguilera": 0.85,
  "Caswell-Massey": 0.85,
  "Romeo Gigli": 0.85,
  "Bruno Acampora": 0.85,
  "Les Perles D'Orient": 0.85,
  "Bottega Veneta": 0.9,
  "Les Parfums de Rosine": 0.95,
  "Bijan": 0.85,
  "Sarah Jessica Parker": 0.85,
  "Sawalef": 0.85,
  "Le Labo": 0.95,
  "Sunnamusk": 0.85,
  "Taylor of London": 0.85,
  "Thameen": 0.85,
  "Ariana Grande": 0.85,
  "Areej Le Doré": 0.85,
  "d'Orsay": 0.85,
  "Katy Perry": 0.85,
  "Kiton": 0.85,
  "Jesus del Pozo": 0.85,
  "Michael Kors": 0.85,
  "Moresque": 0.85,
  "M. Micallef": 0.85,
  "Moschino": 0.85,
  "Panama 1924": 0.85,
  "4160 Tuesdays": 0.85,
  "Agar Aura": 0.85,
  "Al Rehab": 0.8,
  "Alchemic Muse": 0.85,
  "Alyssa Ashley": 0.85,
  "Amir Oud": 0.85,
  "Ard Al Zaafaran / ارض الزعفران التجارية": 0.85,
  "Australian Private Reserve": 0.85,
  "Baldessarini": 0.85,
  "Basile": 0.85,
  "Beacon Mercantile": 0.85,
  "Bond No. 9": 0.9,
  "Botica Botanica": 0.85,
  "Celine": 0.85,
  "Coach": 0.9,
  "Comptoir Sud Pacifique": 0.85,
  "Courrèges": 0.85,
  "Cristiano Ronaldo": 0.85,
  "Ed Hardy": 0.85,
  "Enrico Coveri": 0.85,
  "Fine'ry": 0.85,
  "Féraud": 0.85,
  "Ga-De": 0.85,
  "Geo. F. Trumper": 0.9,
  "Giorgio Beverly Hills": 0.85,
  "Heretic": 0.85,
  "Jean Marc": 0.85,
  "Jean Marc Paris": 0.85,
  "Jimmy Choo": 0.85,
  "John Galliano": 0.85,
  "Lelas": 0.8,
  "Lise Watier": 0.85,
  "Lotto": 0.8,
  "Manzana": 0.85,
  "Mazzolari": 0.85,
  "Nautica": 0.85,
  "Nikos": 0.85,
  "Ortigia": 0.85,
  "Police": 0.85,
  "Rancé 1795": 0.85,
  "Samouraï": 0.85,
  "Shay & Blue": 0.9,
  "Solinotes": 0.85,
  "The 7 Virtues": 0.85,
  "The Harmonist": 0.85,
  "Vasilisa / ヴァシリーサ": 0.85,
  "Victor": 0.85,
  "Wholly Kaw": 0.85,
  "Korloff": 0.85,
  "STR8": 0.85,
  "GDK / Grey de Kouroun": 0.85,
  "Miyaz Perfume": 0.85,
  "Halka B. Organics": 0.85,
  "Carner": 0.85,
  "Replay": 0.85,
  "Helmut Lang": 0.85,
  "Velvet & Sweet Pea's Purrfumery": 0.85,
  "Renato Balestra": 0.85,
  "Abou Jamil Perfumery": 0.85,
  "Helan": 0.85,
  "A & E - Ariana & Evans": 0.85,
  "Prince Matchabelli": 0.85,
  "Primark": 0.85,
  "Filigree & Shadow": 0.85,
  "Pola / ポーラ": 0.85,
  "Playboy": 0.85,
  "Jessica Simpson": 0.85,
  "Tonino Lamborghini": 0.85,
  "Vilhelm Parfumerie": 0.85,
  "Fernanda / フェルナンダ": 0.85,
  "345 Soap Co.": 0.85,
  "Pino Silvestre": 0.85,
  "Demeter Fragrance Library / The Library Of Fragrance": 0.85,
  "Dorothy Gray": 0.85,
  "Giovanni Bacci": 0.85,
  "Alexandra de Markoff": 0.85,
  "Perlier": 0.85,
  "Nicolaï / Parfums de Nicolaï": 0.85,
  "Alghabra": 0.85,
  "Annayake / アナヤケ": 0.85,
  "Dsquared²": 0.85,
  "Nishane": 0.85,
  "Dusita": 0.85,
  "Le Galion": 0.85,
  "Elie Saab": 0.9,
  "Fabergé": 0.85,
  "Aqua Savon / アクア シャボン": 0.85,
  "English Laundry": 0.85,
  "Aramis": 0.85,
  "Marc-Antoine Barrois": 0.85,
  "Stirling Soap": 0.85,
  "Stella McCartney": 0.9,
  "Shulton": 0.85,
  "Mauboussin": 0.85,
  "Sergio Tacchini": 0.85,
  "Maïssa": 0.85,
  "Bait Al Bakhoor": 0.85,
  "Banderas": 0.85,
  "Mercedes-Benz": 0.85,
  "Hamidi Oud & Perfumes": 0.85,
  "Battistoni": 0.85,
  "Jo Loves...": 0.9,
  "Love Passport / ラブ パスポート": 0.85,
  "Michalsky": 0.85,
  "Benetton": 0.85,
  "Jacques Fath": 0.85,
  "Bois 1920": 0.85,
  "Sabon": 0.85,
  "Attar Collection": 0.85,
  "Laboratorio Olfattivo": 0.85,
  "Jeanne Arthes": 0.85,
  "J.F. Schwarzlose Berlin": 0.85,
  "House of Matriarch": 0.85,
  "Laura Ashley": 0.85,
  "Hollister": 0.85,
  "Hind Al Oud / هند العود": 0.85,
  "Le Monde Gourmand": 0.85,
  "Ligne St Barth": 0.85,
  "Heavendüft": 0.85,
  "Widian / AJ Arabia": 0.85,
  "Halloween": 0.85,
  "Luciano Soprani": 0.85,
  "Gritti": 0.85,
  "Gloria Vanderbilt": 0.85,
  "MCMC Fragrances": 0.9,
  "MOR": 0.85,
  "Maison Anthony Marmin / Abdul Karim Al Faransi": 0.85,
  "Giorgio Valenti": 0.85,
  "Metascent": 0.85,
  "MiN New York": 0.85,
  "Germaine Monteil": 0.85,
  "Midnight Gypsy Alchemy": 0.85,
  "Gandini": 0.85,
  "Fyrinnae": 0.85,
  "Montale": 0.9,
  "Montana": 0.85,
  "Morris": 0.85,
  "Flavia": 0.8,
  "Ferrari": 0.85,
  "Mülhens": 0.85,
  "M∙A∙C": 0.85,
  "Naomi Campbell": 0.85,
  "Aerin": 0.85,
  "Navitus Parfums": 0.85,
  "Adolfo Dominguez": 0.85,
  "Nilafar du Nil": 0.85,
  "Noble Otter": 0.85,
  "Extró": 0.85,
  "Acqua di Sardegna": 0.85,
  "Electimuss": 0.8,
  "E&S Rasage": 0.85,
  "Duftanker MGO Duftmanufaktur": 0.85,
  "Dr. Jon's": 0.85,
  "Pierre Guillaume": 0.9,
  "De Ruy": 0.85,
  "Daniel Josier": 0.85,
  "Rasasi": 0.85,
  "Comin": 0.85,
  "Clarins": 0.85,
  "Risingwave / ライジングウェーブ": 0.85,
  "Chiseled Face": 0.85,
  "Roberto Cavalli": 0.85,
  "Roberto Ugolini": 0.85,
  "Chevignon": 0.85,
  "Chatillon Lux": 0.85,
  "Roger & Gallet": 0.85,
  "Byblos": 0.85,
  "Room 1015": 0.85,
  "Roxana Illuminated Perfumes": 0.85,
  "S&C Perfumes / Suchel Camacho": 0.85,
  "S.T. Dupont": 0.85,
  "Beyoncé": 0.85,
  "Abercrombie & Fitch": 0.85,
  "Sarah Horowitz Parfums": 0.85,
  "Sean John": 0.85,
  "Serge Lutens": 0.95,
  "Sergio Soldano": 0.85,
  "Abaton": 0.85,
  "Aēsop": 0.85,
  "Zarkoperfume": 0.85,
  "Solstice Scents": 0.85,
  "Surrati / السرتي": 0.85,
  "Tauer Perfumes": 0.85,
  "Tcheon Fung Sing": 0.85,
  "Arome / Arochem": 0.85,
  "Armand Basi": 0.85,
  "ADN Paris": 0.85,
  "Arabiyat": 0.85,
  "The Man Company": 0.85,
  "Angel Heart / エンジェルハート": 0.85,
  "Tommy Bahama": 0.85,
  "Tommy Hilfiger": 0.85,
  "Tonatto": 0.85,
  "Alcina": 0.85,
  "Alchemessence": 0.85,
  "Valentino": 0.95,
  "Alain Delon": 0.85,
  "Al Fares / الفارس": 0.85,
  "Ajmal": 0.85,
  "Agent Provocateur": 0.85,
  "Vivienne Westwood": 0.85,
  "Khalis / خالص": 0.85,
  "Khadlaj / خدلج": 0.85,
  "Kanebo": 0.85,
  "L'Antichambre": 0.85,
  "L'Erbolario": 0.85,
  "La Martina": 0.85,
  "Maison Margiela": 0.85,
  "MEM Company / M. E. Mayer": 0.85,
  "Touch of Oud": 0.85,
  "Bortnikoff": 0.85,
  "Borsari 1870": 0.85,
  "Boots": 0.85,
  "Jōvan": 0.85,
  "Western Valley": 0.85,
  "Miraculum": 0.85,
  "Miller Harris": 0.9,
  "Gather Perfume / Amrita Aromatics": 0.85,
  "Blumarine": 0.85,
  "Black Oud London": 0.85,
  "Twinkle Apothecary": 0.85,
  "Ulric de Varens": 0.85,
  "Michel Germain": 0.85,
  "Ghost": 0.85,
  "Urban Outfitters": 0.85,
  "Menard": 0.85,
  "Memo Paris": 0.85,
  "Scorpio": 0.85,
  "Kosé / コーセー": 0.85,
  "Jünger & Gebhardt / Patrizier Haus Köln": 0.85,
  "Alain Daniel": 0.85,
  "Womo": 0.85,
  "Gissah / قصة": 0.85,
  "Bachs": 0.85,
  "Matière Première": 0.85,
  "M. Asam": 0.85,
  "Al Halal": 0.85,
  "Kuschel J / クシェルヨット": 0.85,
  "Aéropostale": 0.85,
  "Auric Blends": 0.85,
  "Massimo Dutti": 0.85,
  "Marks & Spencer": 0.85,
  "Aubusson": 0.85,
  "Al Aneeq": 0.85,
  "La Rive": 0.85,
  "Atelier des Ors": 0.85,
  "Heeley": 0.85,
  "Arts&Scents": 0.85,
  "Lancaster": 0.85,
  "Agua de Baleares": 0.85,
  "Expand / エクスパンド": 0.85,
  "One Way Bridge Perfumes": 0.85,
  "Eminence Parfums": 0.85,
  "Orlane / Jean d'Albret": 0.85,
  "Emilio Pucci": 0.85,
  "Teone Reinthal Natural Perfume": 0.85,
  "Ella K Parfums": 0.85,
  "ODE / 80 Acres": 0.85,
  "2 Note": 0.8,
  "El Charro": 0.8,
  "Zoologist": 0.85,
  "Pana Dora": 0.7,
  "100BON": 0.85,
  "Panouge": 0.85,
  "Parfums de Marly": 0.95,
  "Fabled Fragrances": 0.85,
  "Patio": 0.8,
  "Gi. Vi. Emme / Visconti di Modrone": 0.85,
  "Farfalla": 0.85,
  "Perfumer's Workshop": 0.85,
  "The Good Scent.": 0.85,
  "Next": 0.8,
  "Douglas": 0.85,
  "Natural Looks": 0.85,
  "Phebo": 0.85,
  "Di Ser / ディセル": 0.85,
  "Farmasi": 0.85,
  "Pierre Cardin": 0.85,
  "L'Aromatica / Larō": 0.85,
  "John Varvatos": 0.85,
  "Napoleon": 0.8,
  "Fiancée / フィアンセ": 0.85,
  "Fila": 0.85,
  "Yohji Yamamoto": 0.85,
  "Dar Alteeb / دار الطيب": 0.85,
  "Finca / フィンカ": 0.85,
  "Fiorucci": 0.8,
  "Procter & Gamble": 0.85,
  "Aftelier": 0.9,
  "Dame Perfumery Scottsdale": 0.85,
  "Cuba": 0.85,
  "Constance Carroll": 0.85,
  "Flore Botanical Alchemy": 0.85,
  "Gilles Cantuel": 0.85,
  "RazoRock": 0.85,
  "Comme des Garçons": 0.85,
  "Franck Olivier": 0.85,
  "Molyneux": 0.85,
  "Thomas Kosmala": 0.85,
  "Wild Stone": 0.85,
  "Jennifer Lopez": 0.85,
  "Christian Louboutin": 0.95,
  "American Eagle": 0.85,
  "Alphy & Becs": 0.85,
  "Mancera": 0.85,
  "Johann Maria Farina gegenüber dem Jülichs-Platz": 0.85,
  "Kayali": 0.85,
  "Holy Oud": 0.85,
  "Frapin": 0.85
};

// Helper functions
export const getBrandTier = (brandName: string): string => {
  return BRAND_TIER_LOOKUP[brandName] || 'unknown';
};

export const getBrandPriceRange = (brandName: string): string => {
  return BRAND_PRICE_RANGE_LOOKUP[brandName] || 'unknown';
};

export const getBrandConfidence = (brandName: string): number => {
  return BRAND_CONFIDENCE_LOOKUP[brandName] || 0.1;
};

// Brand tier scoring for popularity algorithm
export const BRAND_TIER_SCORES: Record<string, number> = {
  'luxury': 25,
  'high-end-designer': 20,
  'designer': 15,
  'niche': 18,
  'mass-market': 10,
  'unknown': 5
};

export const getBrandTierScore = (brandName: string): number => {
  const tier = getBrandTier(brandName);
  return BRAND_TIER_SCORES[tier] || 5;
};
